### ISSUE TITLE
Pgs stats

### ISSUE THREAD

**Issue by JustHumanz** [digitalocean/ceph_exporter#221]
it's possible to add pgs stat like num of object or size of pg into metrics?

**Comment by baergj** [comment]
Hell @JustHumanz, it would be possible but we've avoided doing this so far because of cardinality concerns - in a large system this could easily lead to too many stats to collect.

I'm not sure whether we (DO) would add this, but patches are welcome; I just ask that the stats be disabled by default with an `envflag` available to turn them on (like how RGW mode works).

**Comment by JustHumanz** [comment]
yeah, that makes sense

actually i have problem with deep-scrubbing stuff and that makes me should do scrubbing manually one by one,the main problem is hard to filter pgs with fewer objects or size 

anyway the thx for answering
