### ISSUE TITLE
ceph_osds_down is returning incorrect count.

### ISSUE THREAD

**Issue by jnials** [digitalocean/ceph_exporter#34]
ceph_osds_down is returning zero (0) when in fact there are a number down.  We are running Jewel.  We can use a workaround of `ceph_osds - ceph_osds_up` because ceph_osds_up seems to be returning correctly.

**Comment by mdlayher** [comment]
I don't actually work with Ceph at all at DO, but my guess would be that this regex is not being matched in Jewel:

https://github.com/digitalocean/ceph_exporter/blob/master/collectors/health.go#L449

Not sure what the equivalent plaintext command would be to get this data.  If you know, would you mind posting a redacted dump with your version of Ceph to see if the regex is incorrect?

**Comment by neurodrone** [comment]
@jnials Thanks for filing this issue! Like @mdlayher mentioned the regex is responsible for pulling the down OSDs from the summary, and since the summary is only visible when HEALTH is WARN or ERR, we don't see the down OSDs once the data is moved and HEALTH becomes OK.

Ceph status doesn't provide us with the no. of down OSDs easily (we didn't want to run `ceph osd tree` specially just to pull count of down OSDs everytime) which is why we did all that gymnastics, but it has its limitations. I will add in a fix that surfaces the value as `num_osds - num_up_osds` which should be accurate.
