### ISSUE TITLE
ceph_cluster_objects and ceph_osd_pgs are not displaying values correctly

### ISSUE THREAD

**Issue by apsega** [digitalocean/ceph_exporter#36]
Hey,

We have issues with `ceph_cluster_objects` and `ceph_osd_pgs` that those are not being displayed correctly.

First of all - `ceph_cluster_objects`. If it shows total number of objects in Ceph, why in our graphs `ceph_misplaced_objects` > `ceph_cluster_objects`?

![screen shot 2016-12-01 at 1 24 39 pm](https://cloud.githubusercontent.com/assets/15917655/20792272/9325aeac-b7c9-11e6-9618-f71aed96bf3a.png)

`ceph_osd_pgs` also is not looking to give us correct values. In our DEV cluster, number of placement groups is always the same - `10560`, but the graph is showing this number varying:

![screen shot 2016-12-01 at 1 27 20 pm](https://cloud.githubusercontent.com/assets/15917655/20792355/f036a556-b7c9-11e6-8393-06fe3d2ed490.png)

Nevertheless, `sum(ceph_osd_pgs)` current value is `30233` and even subtracting by the number of replicas (2), does not equals what `ceph -s` provides - `10560`.

ceph-exporter is running on Docker container and we're using https://grafana.net/dashboards/917 dashboard.

**Comment by neurodrone** [comment]
Hey @apsega, thanks for filing this issue! I will address both those points.

1. `ceph_cluster_objects` is derived from the output of `ceph df detail` command, which doesn't show the count of object replicas. Meanwhile, `ceph_misplaced_objects` pulls the value out of the status summary that includes the replicas as desired. Since it's easier to add a multiple or divisor to either of those values on grafana, I haven't invested much time in looking for the ones with same units. It might help to make this difference apparent in the `help` for each metric.

2. For `ceph_osd_pgs` we are extracting PGs from `ceph osd df` command. When we do it this way, it can potentially include an OSD multiple times, once for each `root` it is a part of. Do you have multiple roots i.e. other than `default`? I can check if there's a better way to group them w.r.t each root.

**Comment by apsega** [comment]
@neurodrone thanks for your prompt response.

Is there a list which metrics are being displayed replicated and which not replicated? 

Regarding `ceph_osd_pgs` - it would definitely be great if you could find a better way of grouping it.

What I see is that `ceph_osd_pgs` takes values from `ceph df detail` (8kk objects), while misplaced objects are taken from `ceph -s` and there total number of total objects is 23kk (`13113512/23673533 objects misplaced`):

```
2016-12-01 14:18:01.748741 mon.0 [INF] pgmap v45800318: 10560 pgs: 1 active+recovery_wait+degraded, 2 remapped, 6 remapped+peering, 3 active+undersized+degraded+remapped+backfilling, 33 active+undersized+degraded, 25 active+undersized+degraded+remapped+wait_backfill, 26 active+remapped+backfilling, 7940 active+remapped+wait_backfill, 2524 active+clean; 33313 GB data, 66851 GB used, 67219 GB / 130 TB avail; 7621 B/s rd, 255 kB/s wr, 24 op/s; 46217/23673533 objects degraded (0.195%); 13113512/23673533 objects misplaced (55.393%); 1266 MB/s, 316 objects/s recovering
```

Attaching `ceph df detail` and `ceph osd df` output:
[ceph_df_detail.txt](https://github.com/digitalocean/ceph_exporter/files/624648/ceph_df_detail.txt)
[ceph_osd_df.txt](https://github.com/digitalocean/ceph_exporter/files/624652/ceph_osd_df.txt)

**Comment by neurodrone** [comment]
> Is there a list which metrics are being displayed replicated and which not replicated? 

Not yet. I intend to add the information in the `Help` field of every metric starting with the two we encountered.

> Regarding ceph_osd_pgs - it would definitely be great if you could find a better way of grouping it.

This will be a bit tricky, since the `root` is not present in the `ceph osd df` or even the more detailed `ceph osd df  --format json`. Also if you sum up the PGs they will be summed up across each pool, and the replication factor or EC parity count will be specific to each pool. I don't think we need to jump through so many hoops to get the PG count, I will add a fix for it today to simple extract it from `num_pgs`.

**Comment by apsega** [comment]
Cool! I'll be waiting for the update then.

Still I'm a bit confused regarding `ceph_cluster_objects` which shows 8kk objects (pulls from `ceph df detail`) and `ceph_misplaced_objects` which shows 13kk misplaced out of 23kk (pulls from `ceph -s`?). 

As I understand `ceph df detail` and `ceph -s` have different definitions of `object` and taking misplaced objects and total objects values from both of them could be wrong.

**Comment by neurodrone** [comment]
I can help explain that. Can you attach the output of `ceph osd pool ls detail` by any chance?

**Comment by apsega** [comment]
Sorry for leading you wrong, I meant `ceph -w` (not `ceph -s`) and it only shows greatly bigger number of objects when they're misplaced. Here's the output of `ceph osd pool ls detail`:
[ceph_osd_pool_ls_detail.txt](https://github.com/digitalocean/ceph_exporter/files/624757/ceph_osd_pool_ls_detail.txt)

**Comment by neurodrone** [comment]
No worries! They both should show the same output.

All your pools are replicated and seem to have a `replication factor` of 2 like you mentioned earlier, which means the actual object count should be twice what `ceph -s` says which is `8562684 * 2 = 17125368`. 13M seems less than 17M so that's good in a way, but I am not sure where the 23M comes from.

Did you delete any files from the object store or trim any block store volumes? One way to check would be to stop a single OSD for a few seconds and watch the `ceph status` to see what's the proportion of "objects degraded" it points to.

**Comment by apsega** [comment]
Seems like we hit Ceph bug - https://bugzilla.redhat.com/show_bug.cgi?id=1254398. 

Anyway, @neurodrone thanks for everything!

**Comment by neurodrone** [comment]
Once https://github.com/digitalocean/ceph_exporter/pull/37 goes in your should be able to get the total PGs for your cluster via `ceph_total_pgs` metric.
