### ISSUE TITLE
Add host label to OSDs

### ISSUE THREAD

**Issue by bluecmd** [digitalocean/ceph_exporter#40]
Hi,

When debugging OSD latency issues it would be very helpful if there was a label connecting the OSD to the host (like the output of `ceph osd tree`).

It would also disambiguate if the OSD ever moves to another host.

**Comment by neurodrone** [comment]
That would be nice indeed. Ideally it would be nice not to run `ceph osd tree` every time we want the information about host->osd mapping, especially because that information is going to change very infrequently/never, but at the same time it'd be nice to know what the new mapping is if/when changes do happen.

**Comment by apsega** [comment]
This would really help us, too! Are you going to implement this eventually?

**Comment by cristicalin** [comment]
We are looking to implement this approach but the problem here is that if you have multiple roots, an OSD can appear in multiple places in the tree (i.e. you keep the default around and use an SSD and a SAS root).
In this situation which host should appear in the label ?

We also want to add the entire path (room, rack, host) how should we best add this information? I'm thinking we can add this tree in a separate metric so as not to pollute the other metrics and use it in a lookup in a template variable in grafana to fetch the OSD ID and then restrict the selection.

Any idea is welcomed.

**Comment by apsega** [comment]
For us, host label would really help in alerting and silences cases. I.e. when we're shutting down/rebooting several hosts, it's really inconvenient to setup silence on `ceph_osds_down` metric with huge regex of OSDs that are on that hose. If we could only specify host that'd help a lot!

**Comment by alram** [comment]
A bit late to the party but this was added as part of https://github.com/digitalocean/ceph_exporter/pull/147, closing
