### ISSUE TITLE
ceph_client_io_(read|write)_ops always zero

### ISSUE THREAD

**Issue by epgrvp** [digitalocean/ceph_exporter#45]
Hi,

with ceph hammer I get inclomplete values for the ioops

```
# HELP ceph_cache_promote_io_ops Total cache promote operations measured per second
# TYPE ceph_cache_promote_io_ops gauge
ceph_cache_promote_io_ops 0
# HELP ceph_client_io_ops Total client ops on the cluster measured per second
# TYPE ceph_client_io_ops gauge
ceph_client_io_ops 111
# HELP ceph_client_io_read_ops Total client read I/O ops on the cluster measured per second
# TYPE ceph_client_io_read_ops gauge
ceph_client_io_read_ops 0
# HELP ceph_client_io_write_ops Total client write I/O ops on the cluster measured per second
# TYPE ceph_client_io_write_ops gauge
ceph_client_io_write_ops 0

```
Is this a problem of the hammer relase?

Regards, Eckebrecht

**Comment by mdlayher** [comment]
This issue seems familiar to me.  I'll defer to @neurodrone on this one as he probably knows more about which metrics were available in which Ceph releases.

**Comment by neurodrone** [comment]
@epgrvp Can you paste a sample output of `ceph -s` from the cluster you are running Hammer on?

**Comment by epgrvp** [comment]
Sure ;)

`ceph -s
    cluster xxxxxxxxxxxxxxxxx
     health HEALTH_OK
     monmap e9: 3 mons at {a=192.168.29.38:6789/0,b=192.168.29.39:6789/0,c=192.168.2
9.40:6789/0}
            election epoch 410, quorum 0,1,2 a,b,c
     osdmap e22832: 18 osds: 18 up, 18 in
      pgmap v52893688: 6688 pgs, 18 pools, 4835 GB data, 4683 kobjects
            14761 GB used, 17326 GB / 32087 GB avail
                6688 active+clean
  client io 3134 kB/s rd, 75295 B/s wr, 88 op/s`

**Comment by neurodrone** [comment]
You are right, that will not work. Jewel added a change to this format and introduced `op/s rd` and `op/s wr` that is presently supported by ceph exporter. We don't have version-specific releases yet but that would be nice to have at some point because of all the changes (some not backward-compatible) introduced in every version.

**Comment by epgrvp** [comment]
Ok, thanks for investigating. Still this exporter is quite helpful, thanks for that.

**Comment by unixwitch** [comment]
This is broken again on Luminous (tested with 12.1.0 RC, ceph_exporter 1.1.0):

```
root@ceph-1-mon-3:~# ceph -s
  cluster:
    id:     5c475082-d8ac-4552-8a47-a77bc3666daa
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c
    mgr: a(active), standbys: b, c
    mds: 1/1/1 up {0=b=up:active}, 1 up:standby-replay
    osd: 3 osds: 3 up, 3 in
 
  data:
    pools:   3 pools, 320 pgs
    objects: 131k objects, 102294 MB
    usage:   211 GB used, 89982 MB / 299 GB avail
    pgs:     320 active+clean
 
  io:
    client:   1279 B/s rd, 47684 B/s wr, 2 op/s rd, 1 op/s wr
```

Luminous will be the new LTS release fairly soon, so it would be nice to have this working.

**Comment by neurodrone** [comment]
Luminous adds both client I/O and recovery I/O stats to the json format, so it would be easier to process it compared to the work we were doing extracting it out of plaintext. The idea however would be to make that change in a backwards compatible manner in order to keep supporting Jewel format since I believe not everyone who's using the exporter can upgrade their production clusters to Luminous immediately.

**Comment by EmilioD** [comment]
where is that text being parsed out? I too have the same issue after upgrading to Luminous. pulling from JSON makes the most sense long term.
